#!/usr/bin/env python3
"""
Test runner script for Polymarket Trading Bot
Generates comprehensive test reports
"""

import os
import sys
import subprocess
import argparse
from datetime import datetime

def run_tests(test_type='all', coverage=True, html_report=True):
    """Run tests and generate reports"""
    
    # Create test reports directory
    os.makedirs('test_reports', exist_ok=True)
    
    # Base pytest command
    cmd = ['python', '-m', 'pytest']
    
    # Add test selection
    if test_type == 'unit':
        cmd.extend(['-m', 'not integration'])
    elif test_type == 'integration':
        cmd.extend(['-m', 'integration'])
    elif test_type == 'all':
        cmd.append('tests/')
    
    # Add coverage
    if coverage:
        cmd.extend([
            '--cov=.',
            '--cov-report=html:test_reports/coverage',
            '--cov-report=term-missing',
            '--cov-report=xml:test_reports/coverage.xml'
        ])
    
    # Add HTML report
    if html_report:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        cmd.extend([
            f'--html=test_reports/test_report_{timestamp}.html',
            '--self-contained-html'
        ])
    
    # Add other options
    cmd.extend([
        '-v',
        '--tb=short',
        '--strict-markers'
    ])
    
    print(f"Running command: {' '.join(cmd)}")
    
    # Run tests
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    # Print results
    print("STDOUT:")
    print(result.stdout)
    
    if result.stderr:
        print("STDERR:")
        print(result.stderr)
    
    print(f"Return code: {result.returncode}")
    
    # Generate summary report
    generate_summary_report(result, test_type)
    
    return result.returncode

def generate_summary_report(result, test_type):
    """Generate a summary report of test results"""
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    report = f"""
# Polymarket Trading Bot - Test Report

**Generated:** {timestamp}  
**Test Type:** {test_type}  
**Exit Code:** {result.returncode}

## Test Results

```
{result.stdout}
```

## Coverage Reports
- HTML Coverage Report: `test_reports/coverage/index.html`
- XML Coverage Report: `test_reports/coverage.xml`

## Test Execution Details
- **Command:** pytest {' '.join(sys.argv[1:]) if len(sys.argv) > 1 else ''}
- **Environment:** Python {sys.version}
- **Working Directory:** {os.getcwd()}

## Status
{'✅ PASSED' if result.returncode == 0 else '❌ FAILED'}

---
*Generated by Polymarket Trading Bot Test Runner*
"""
    
    with open('test_reports/summary.md', 'w') as f:
        f.write(report)
    
    print(f"\nSummary report generated: test_reports/summary.md")

def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(description='Run Polymarket Trading Bot tests')
    parser.add_argument('--type', choices=['all', 'unit', 'integration'], 
                       default='all', help='Type of tests to run')
    parser.add_argument('--no-coverage', action='store_true', 
                       help='Skip coverage report generation')
    parser.add_argument('--no-html', action='store_true', 
                       help='Skip HTML report generation')
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("Polymarket Trading Bot - Test Runner")
    print("=" * 60)
    
    exit_code = run_tests(
        test_type=args.type,
        coverage=not args.no_coverage,
        html_report=not args.no_html
    )
    
    print("=" * 60)
    if exit_code == 0:
        print("✅ All tests passed!")
    else:
        print("❌ Some tests failed!")
    print("=" * 60)
    
    sys.exit(exit_code)

if __name__ == '__main__':
    main()
